import Anthropic from '@anthropic-ai/sdk';
import { CompanyProfile } from './companyProfiler';

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

/**
 * A single ICP persona generated by Agent 2
 */
export interface ICPPersona {
  id: string; // e.g., "icp_a", "icp_b"
  name: string; // e.g., "The Scaling Startup Founder"
  
  // Who they are
  titles: string[];
  seniority: 'c-level' | 'vp' | 'director' | 'manager' | 'individual-contributor';
  department: string;
  
  // Where they work
  companySize: string;
  companyStage: string;
  industries: string[];
  
  // Their situation
  painPoints: string[];
  goals: string[];
  dayToDay: string;
  
  // Why they'd buy
  buyingTriggers: string[];
  valueTheySeek: string;
  
  // Reasoning
  whyThisPersona: string;
}

/**
 * Output from Agent 2
 */
export interface ICPBrainstormResult {
  personas: ICPPersona[];
  reasoning: string;
  debug: {
    prompt: string;
    response: string;
  };
}

/**
 * Agent 2: ICP Brainstormer
 * 
 * Focused task: Given a company profile, brainstorm ALL the potential
 * buyer personas who could benefit from this product/service.
 * 
 * Does NOT pick the best one or decide LinkedIn filters - just generates options.
 */
export async function brainstormICPs(
  companyProfile: CompanyProfile
): Promise<ICPBrainstormResult> {
  console.log(`[Agent2:ICPBrainstormer] Generating personas for ${companyProfile.name}...`);
  const startTime = Date.now();

  const prompt = `You are an expert sales strategist. Your job is to brainstorm ALL potential ideal customer profiles (ICPs) for a company.

## Company Profile

Name: ${companyProfile.name}
Product/Service: ${companyProfile.productOrService}
Problem They Solve: ${companyProfile.problemTheySolve}
How They Solve It: ${companyProfile.howTheySolveIt}
Target Market: ${companyProfile.targetMarket}
Existing Customers: ${companyProfile.existingCustomerTypes.join(', ') || 'Unknown'}
Industry: ${companyProfile.industry}
Competitive Advantage: ${companyProfile.competitiveAdvantage}
Pricing Model: ${companyProfile.pricingModel}
Company Maturity: ${companyProfile.companyMaturity}
Sales Motion: ${companyProfile.salesMotion}

## Your Task

Generate 4-5 DISTINCT buyer personas who could benefit from this company's offering. Think broadly:

1. The obvious buyer (who they clearly target)
2. The adjacent buyer (related role or industry)
3. The upstream buyer (someone earlier in the value chain)
4. The downstream buyer (someone later in the value chain)
5. The unexpected buyer (a non-obvious use case)

For each persona, think about:
- What job titles would this person have?
- What's their day-to-day like?
- What pain points does this product solve for them?
- What would trigger them to look for a solution?

Respond with ONLY valid JSON:

{
  "personas": [
    {
      "id": "icp_a",
      "name": "The [Descriptive Name]",
      "titles": ["VP of Sales", "Head of Sales", "Sales Director"],
      "seniority": "vp",
      "department": "Sales",
      "companySize": "50-200 employees",
      "companyStage": "Series A/B startup",
      "industries": ["SaaS", "B2B Tech"],
      "painPoints": ["Pain 1", "Pain 2"],
      "goals": ["Goal 1", "Goal 2"],
      "dayToDay": "Brief description of their typical day",
      "buyingTriggers": ["Trigger 1", "Trigger 2"],
      "valueTheySeek": "What value they'd get from this product",
      "whyThisPersona": "Why this persona makes sense for this company"
    }
  ],
  "reasoning": "Overall reasoning about the ICP landscape for this company"
}

Be creative but realistic. Each persona should be meaningfully different.`;

  const message = await anthropic.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 2048,
    messages: [
      {
        role: 'user',
        content: prompt,
      },
    ],
  });

  const responseText = message.content[0].type === 'text' ? message.content[0].text : '';
  
  const jsonMatch = responseText.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    throw new Error('[Agent2:ICPBrainstormer] Failed to parse response as JSON');
  }

  const parsed = JSON.parse(jsonMatch[0]);
  
  const result: ICPBrainstormResult = {
    personas: parsed.personas,
    reasoning: parsed.reasoning,
    debug: {
      prompt,
      response: responseText,
    },
  };
  
  const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
  console.log(`[Agent2:ICPBrainstormer] Complete in ${elapsed}s - Generated ${result.personas.length} personas`);

  return result;
}

