import Anthropic from '@anthropic-ai/sdk';
import { CompanyProfile } from './companyProfiler';

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

/**
 * Clean up common LLM JSON output issues before parsing
 */
function cleanJsonString(str: string): string {
  return str
    // Remove trailing commas before ] or }
    .replace(/,(\s*[}\]])/g, '$1')
    // Remove any control characters that might sneak in
    .replace(/[\x00-\x1F\x7F]/g, (match) => {
      // Keep newlines, tabs, carriage returns (they're valid in JSON strings when escaped)
      if (match === '\n' || match === '\r' || match === '\t') return match;
      return '';
    });
}

/**
 * A single ICP persona generated by Agent 2
 */
export interface ICPPersona {
  id: string; // e.g., "icp_a", "icp_b"
  name: string; // e.g., "The Scaling Startup Founder"
  
  // Who they are
  titles: string[];
  seniority: 'c-level' | 'vp' | 'director' | 'manager' | 'individual-contributor';
  department: string;
  
  // Where they work
  companySize: string;
  companyStage: string;
  industries: string[];
  
  // Their situation
  painPoints: string[];
  goals: string[];
  dayToDay: string;
  
  // Why they'd buy
  buyingTriggers: string[];
  valueTheySeek: string;
  
  // Reasoning
  whyThisPersona: string;
}

/**
 * Output from Agent 2
 */
export interface ICPBrainstormResult {
  personas: ICPPersona[];
  reasoning: string;
  debug: {
    prompt: string;
    response: string;
  };
}

/**
 * Agent 2: ICP Brainstormer
 * 
 * Focused task: Given a company profile, brainstorm ALL the potential
 * buyer personas who could benefit from this product/service.
 * 
 * Does NOT pick the best one or decide LinkedIn filters - just generates options.
 */
export async function brainstormICPs(
  companyProfile: CompanyProfile
): Promise<ICPBrainstormResult> {
  console.log(`[Agent2:ICPBrainstormer] Generating personas for ${companyProfile.name}...`);
  const startTime = Date.now();

  const prompt = `You are an expert sales strategist. Your job is to brainstorm ALL potential ideal customer profiles (ICPs) for a company.

## Company Profile

Name: ${companyProfile.name}
Product/Service: ${companyProfile.productOrService}
Problem They Solve: ${companyProfile.problemTheySolve}
How They Solve It: ${companyProfile.howTheySolveIt}
Target Market: ${companyProfile.targetMarket}
Existing Customers: ${companyProfile.existingCustomerTypes.join(', ') || 'Unknown'}
Industry: ${companyProfile.industry}
Competitive Advantage: ${companyProfile.competitiveAdvantage}
Pricing Model: ${companyProfile.pricingModel}
Company Maturity: ${companyProfile.companyMaturity}
Sales Motion: ${companyProfile.salesMotion}

## Geographic Focus (Where This Company Sells)

Primary Markets: ${companyProfile.geography?.primaryMarkets?.join(', ') || 'Unknown'}
Office Locations: ${companyProfile.geography?.officeLocations?.join(', ') || 'Unknown'}
Geographic Confidence: ${companyProfile.geography?.confidence || 'Unknown'}
Reasoning: ${companyProfile.geography?.reasoning || 'No geographic analysis available'}

⚠️ Consider these geographies when thinking about buyer personas. A company based in the UK selling to UK businesses will have different buyers than a global SaaS company.

## Case Studies & Testimonials (PAY CLOSE ATTENTION - these reveal who ACTUALLY buys)

${companyProfile.caseStudiesOrTestimonials.length > 0 
  ? companyProfile.caseStudiesOrTestimonials.map((cs, i) => `${i + 1}. ${cs}`).join('\n')
  : 'None found on website'}

⚠️ The case studies above are GOLD - they tell you who has ACTUALLY purchased, not just who the company thinks they sell to. Weight these heavily when generating personas.

## Your Task

Generate 4-5 DISTINCT buyer personas who could benefit from this company's offering. Think broadly:

1. The obvious buyer (who they clearly target)
2. The adjacent buyer (related role or industry)
3. The upstream buyer (someone earlier in the value chain)
4. The downstream buyer (someone later in the value chain)
5. The unexpected buyer (a non-obvious use case)

## CRITICAL: Title Rules

Each persona's "titles" array must contain ONLY variations of the SAME core role:

✅ GOOD (tight, focused):
- ["VP of Sales", "Head of Sales", "Director of Sales"] — all sales leaders
- ["CEO", "Founder", "Co-Founder", "Owner"] — all company owners
- ["Head of Growth", "VP of Growth", "Growth Lead"] — all growth leaders
- ["RevOps Manager", "Revenue Operations Lead", "Sales Ops Manager"] — all ops roles

❌ BAD (scattered, unfocused):
- ["Account Director", "VP of Client Services", "Agency Partner"] — these are 3 different jobs
- ["CEO", "VP of Sales", "Marketing Manager"] — mixing levels and functions
- ["Founder", "Head of Product", "Engineering Manager"] — different departments

The titles should be what you'd put in a LinkedIn search to find THE SAME TYPE OF PERSON at different companies. If the titles would return completely different people, you've gone too broad.

Respond with ONLY valid JSON:

{
  "personas": [
    {
      "id": "icp_a",
      "name": "The [Descriptive Name]",
      "titles": ["VP of Sales", "Head of Sales", "Director of Sales"],
      "seniority": "vp",
      "department": "Sales",
      "companySize": "50-200 employees",
      "companyStage": "Series A/B startup",
      "industries": ["SaaS", "B2B Tech"],
      "painPoints": ["Pain 1", "Pain 2"],
      "goals": ["Goal 1", "Goal 2"],
      "dayToDay": "Brief description of their typical day",
      "buyingTriggers": ["Trigger 1", "Trigger 2"],
      "valueTheySeek": "What value they'd get from this product",
      "whyThisPersona": "Why this persona makes sense for this company"
    }
  ],
  "reasoning": "Overall reasoning about the ICP landscape for this company"
}

Be opinionated. Each persona should represent ONE clear role archetype with tight title variations.`;

  const message = await anthropic.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 200000,
    messages: [
      {
        role: 'user',
        content: prompt,
      },
    ],
  });

  const responseText = message.content[0].type === 'text' ? message.content[0].text : '';
  
  const jsonMatch = responseText.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    throw new Error('[Agent2:ICPBrainstormer] Failed to parse response as JSON');
  }

  let parsed;
  try {
    const cleanedJson = cleanJsonString(jsonMatch[0]);
    parsed = JSON.parse(cleanedJson);
  } catch (parseError) {
    console.error('[Agent2:ICPBrainstormer] JSON parse error:', parseError);
    console.error('[Agent2:ICPBrainstormer] Raw response (first 500 chars):', jsonMatch[0].substring(0, 500));
    throw new Error(`[Agent2:ICPBrainstormer] Failed to parse JSON: ${parseError instanceof Error ? parseError.message : 'Unknown error'}`);
  }
  
  const result: ICPBrainstormResult = {
    personas: parsed.personas,
    reasoning: parsed.reasoning,
    debug: {
      prompt,
      response: responseText,
    },
  };
  
  const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
  console.log(`[Agent2:ICPBrainstormer] Complete in ${elapsed}s - Generated ${result.personas.length} personas`);

  return result;
}

